#pragma once
#include<SFML\Graphics.hpp>
#include<sstream>
typedef sf::Texture IMG;
using namespace std;
class Texture
{
public:

	IMG Logo;
	IMG SFML;
	IMG EnterText;
	IMG Button;
	IMG Marker;
	IMG Glow, Shine, Combo;
	IMG Flour;
	IMG PlayerTopBar, RecordTable;
	IMG Cloud;
	IMG PortalKeyCrematory;
	IMG PortalEpic, PortalFire, PortalFrost, PortalNature, PortalTeleport;
	IMG BonusIndBar, BonusIndEpic, BonusIndFire, BonusIndFrost, BonusIndNature;
	IMG PortalEffectEpic, PortalEffectFire, PortalEffectFrost, PortalEffectNature, PortalDark;
	IMG PortalEffectTornadoEpic, PortalEffectTornadoFire, PortalEffectTornadoFrost, PortalEffectTornadoNature;
	IMG RingEpic, RingFire, RingFrost, RingNature, RingBlack, RingWhite;
	IMG SphereFire, SphereFrost, SphereEpic, SphereNature, SphereBlack, SphereWhite;
	IMG KeyCreator;
	IMG BangFrost, BangFire, BangEpic, BangNature, BangBlack, BangWhite;
	IMG WaterMultipleEffect;
	IMG Key, Symbols_EN, Symbols_RU;
	IMG EffectRainbow, BallRainbow;
	IMG Galaxy1, Galaxy2, Galaxy3, Galaxy4, Galaxy5, Galaxy6, Galaxy7, Galaxy8;
	IMG Star1, Star2, Star3, Star4;
	IMG SpaceBlack;
	IMG Fire, Frost, Dark, Life;
	IMG LevelFailed;
	IMG Scroller, VolumeScroll, CheckBox;
	IMG Pause;
	IMG Diff_Easy, Diff_Hard, Diff_Norm;
	IMG TeleportEff1, TeleportEff2;
	IMG UFO, UFO2;
	IMG Boss1;
	IMG Turret, Wheel;
	IMG Shadow;
	IMG Laser, LaserEffect;
	IMG EffectInBoss1;
	IMG BangBoss;
	IMG Destroyer;
	IMG Boss2;
	IMG PirateStation;
	IMG Spider;
	IMG Locust;
	IMG GopherQuad;
	IMG CatchGopher;
	IMG Meteor;
	IMG Light;
	IMG Border;
	IMG White;
	IMG Rainbow2;
	IMG LocustLogo;
	IMG RockFall;
private:

	inline void Load(IMG& texture, const string& file)
	{
		texture.loadFromFile("Resources/Textures/"+file);
	}

public: 

	void setSmoth(bool isSmoth)
	{
		Logo.setSmooth(isSmoth);
		RockFall.setSmooth(isSmoth);
		LocustLogo.setSmooth(isSmoth);
		Rainbow2.setSmooth(isSmoth);
		White.setSmooth(isSmoth);
		Border.setSmooth(isSmoth);
		PlayerTopBar.setSmooth(isSmoth);
		EnterText.setSmooth(isSmoth);
		Button.setSmooth(isSmoth);
		Glow.setSmooth(isSmoth);
		Marker.setSmooth(isSmoth);
		Flour.setSmooth(isSmoth);
		PortalKeyCrematory.setSmooth(isSmoth);
		WaterMultipleEffect.setSmooth(isSmoth);
		PortalEffectEpic.setSmooth(isSmoth);
		PortalEffectFire.setSmooth(isSmoth);
		PortalEffectFrost.setSmooth(isSmoth);
		PortalEffectNature.setSmooth(isSmoth);
		PortalEffectTornadoEpic.setSmooth(isSmoth);
		PortalEffectTornadoFire.setSmooth(isSmoth);
		PortalEffectTornadoFrost.setSmooth(isSmoth);
		PortalEffectTornadoNature.setSmooth(isSmoth);
		PortalEpic.setSmooth(isSmoth);
		PortalFire.setSmooth(isSmoth);
		PortalFrost.setSmooth(isSmoth);
		PortalNature.setSmooth(isSmoth);
		PortalDark.setSmooth(isSmoth);
		PortalTeleport.setSmooth(isSmoth);
		RingEpic.setSmooth(isSmoth);
		RingFire.setSmooth(isSmoth);
		RingFrost.setSmooth(isSmoth);
		RingNature.setSmooth(isSmoth);
		RingBlack.setSmooth(isSmoth);
		RingWhite.setSmooth(isSmoth);
		KeyCreator.setSmooth(isSmoth);
		BangFire.setSmooth(isSmoth);
		BangFrost.setSmooth(isSmoth);
		BangEpic.setSmooth(isSmoth);
		BangNature.setSmooth(isSmoth);
		BangBlack.setSmooth(isSmoth);
		BangWhite.setSmooth(isSmoth);
		SphereFire.setSmooth(isSmoth);
		SphereFrost.setSmooth(isSmoth);
		SphereEpic.setSmooth(isSmoth);
		SphereNature.setSmooth(isSmoth);
		SphereBlack.setSmooth(isSmoth);
		SphereWhite.setSmooth(isSmoth);
		Shine.setSmooth(isSmoth);
		Cloud.setSmooth(isSmoth);
		Key.setSmooth(isSmoth);
		Symbols_EN.setSmooth(isSmoth);
		Symbols_RU.setSmooth(isSmoth);
		EffectRainbow.setSmooth(isSmoth);
		BallRainbow.setSmooth(isSmoth);
		Galaxy1.setSmooth(isSmoth);
		Galaxy2.setSmooth(isSmoth);
		Galaxy3.setSmooth(isSmoth);
		Galaxy4.setSmooth(isSmoth);
		Galaxy5.setSmooth(isSmoth);
		Galaxy6.setSmooth(isSmoth);
		Galaxy7.setSmooth(isSmoth);
		Galaxy8.setSmooth(isSmoth);
		Star1.setSmooth(isSmoth);	
		Star2.setSmooth(isSmoth);	
		Star3.setSmooth(isSmoth);
		Star4.setSmooth(isSmoth);
		Fire.setSmooth(isSmoth);
		Frost.setSmooth(isSmoth);
		Dark.setSmooth(isSmoth);
		Life.setSmooth(isSmoth);
		LevelFailed.setSmooth(isSmoth);
		BonusIndBar.setSmooth(isSmoth);
		BonusIndEpic.setSmooth(isSmoth);
		BonusIndFire.setSmooth(isSmoth);
		BonusIndFrost.setSmooth(isSmoth);
		BonusIndNature.setSmooth(isSmoth);
		Combo.setSmooth(isSmoth);
		RecordTable.setSmooth(isSmoth);
		SpaceBlack.setSmooth(isSmoth);
		Scroller.setSmooth(isSmoth);
		VolumeScroll.setSmooth(isSmoth);
		CheckBox.setSmooth(isSmoth);
		Pause.setSmooth(isSmoth);
		Diff_Easy.setSmooth(isSmoth);
		Diff_Hard.setSmooth(isSmoth);
		Diff_Norm.setSmooth(isSmoth);
		TeleportEff1.setSmooth(isSmoth);
		TeleportEff2.setSmooth(isSmoth);
		UFO.setSmooth(isSmoth);
		Boss1.setSmooth(isSmoth);
		Turret.setSmooth(isSmoth);
		Wheel.setSmooth(isSmoth);
		Shadow.setSmooth(isSmoth);
		Laser.setSmooth(isSmoth);
		LaserEffect.setSmooth(isSmoth);
		EffectInBoss1.setSmooth(isSmoth);
		BangBoss.setSmooth(isSmoth);
		Destroyer.setSmooth(isSmoth);
		PirateStation.setSmooth(isSmoth);
		Boss2.setSmooth(isSmoth);
		Spider.setSmooth(isSmoth);
		Locust.setSmooth(isSmoth);
		GopherQuad.setSmooth(isSmoth);
		CatchGopher.setSmooth(isSmoth);
		Meteor.setSmooth(isSmoth);
		Light.setSmooth(isSmoth);
		UFO2.setSmooth(isSmoth);
		SFML.setSmooth(isSmoth);
	}

	Texture()
	{
		Load( Logo,							"Logo.png"						);
		Load( RockFall,						"RockFall.png"					);
		Load( LocustLogo,					"LocustLogo.png"				);
		Load( PlayerTopBar,					"PlayerTopBar.jpg"				);
		Load( EnterText,					"EnterText.png"					);
		Load( Button,						"Button.png"					);
		Load( Glow,							"Glow.png"						);
		Load( Scroller,						"Scroller.png"					);
		Load( VolumeScroll,					"VolumeScroll.png"				);
		Load( CheckBox,						"CheckBox.png"					);
		Load( Marker,						"Marker.png"					);
		Load( Flour,						"Flour.png"						);
		Load( PortalKeyCrematory,			"PortalKeyCrematory.png"		);
		Load( WaterMultipleEffect,			"WaterMultipleEffect.png"		);
		Load( PortalEffectEpic,				"PortalEffectEpic.png"			);
		Load( PortalEffectFire,				"PortalEffectFire.png"			);
		Load( PortalEffectFrost,			"PortalEffectFrost.png"			);
		Load( PortalEffectNature,			"PortalEffectNature.png"		);
		Load( PortalEffectTornadoEpic,		"PortalEffectTornadoEpic.png"	);
		Load( PortalEffectTornadoFire,		"PortalEffectTornadoFire.png"	);
		Load( PortalEffectTornadoFrost,		"PortalEffectTornadoFrost.png"	);
		Load( PortalEffectTornadoNature,	"PortalEffectTornadoNature.png"	);
		Load( PortalEpic,					"PortalEpic.png"				);
		Load( PortalFire,					"PortalFire.png"				);
		Load( PortalFrost,					"PortalFrost.png"				);
		Load( PortalNature,					"PortalNature.png"				);
		Load( PortalDark,					"PortalDark.png"				);
		Load( PortalTeleport,				"Teleport.png"					);
		Load( RingEpic,						"RingEpic.png"					);
		Load( RingFire,						"RingFire.png"					);
		Load( RingFrost,					"RingFrost.png"					);
		Load( RingNature,					"RingNature.png"				);
		Load( RingBlack,					"RingBlack.png"					);
		Load( RingWhite,					"RingWhite.png"					);
		Load( KeyCreator,					"KeyCreator.png"				);
		Load( BangFire,						"BangFire.png"					);
		Load( BangFrost,					"BangFrost.png"					);
		Load( BangEpic,						"BangEpic.png"					);
		Load( BangNature,					"BangNature.png"				);
		Load( BangBlack,					"BangBlack.png"					);
		Load( BangWhite,					"BangWhite.png"					);
		Load( SphereFire,					"SphereFire.png"				);
		Load( SphereFrost,					"SphereFrost.png"				);
		Load( SphereEpic,					"SphereEpic.png"				);
		Load( SphereNature,					"SphereNature.png"				);
		Load( SphereBlack,					"SphereBlack.png"				);
		Load( SphereWhite,					"SphereWhite.png"				);
		Load( Shine,						"Shine.png"						);
		Load( Cloud,						"Cloud.png"						);
		Load( Key,							"Key.png"						);
		Load( Symbols_EN,					"Symbols_EN.png"				);
		Load( Symbols_RU,					"Symbols_RU.png"				);
		Load( EffectRainbow,				"EffectRainbow.png"				);
		Load( BallRainbow,					"BallRainbow.png"				);
		Load( Galaxy1,						"Galaxy1.png"					);
		Load( Galaxy2,						"Galaxy2.png"					);
		Load( Galaxy3,						"Galaxy3.png"					);
		Load( Galaxy4,						"Galaxy4.png"					);
		Load( Galaxy5,						"Galaxy5.png"					);
		Load( Galaxy6,						"Galaxy6.png"					);
		Load( Galaxy7,						"Galaxy7.png"					);
		Load( Galaxy8,						"Galaxy8.png"					);
		Load( Star1,						"Star1.png"						);
		Load( Star2,						"Star2.png"						);
		Load( Star3,						"Star3.png"						);
		Load( Star4,						"Star4.png"						);
		Load( Diff_Easy,					"diff_Easy.png"					);
		Load( Diff_Hard,					"diff_Hard.png"					);
		Load( Diff_Norm,					"diff_Norm.png"					);
		Load( Fire,							"LogoFire.png"					);
		Load( Frost,						"LogoFrost.png"					);
		Load( Dark,							"LogoDark.png"					);
		Load( Life,							"LogoLife.png"					);
		Load( LevelFailed,					"LevelFailed.png"				);
		Load( BonusIndBar,					"BonusIndBar.png"				);
		Load( BonusIndEpic,					"BonusIndEpic.jpg"				);
		Load( BonusIndFire,					"BonusIndFire.jpg"				);
		Load( BonusIndFrost,				"BonusIndFrost.jpg"				);
		Load( BonusIndNature,				"BonusIndNature.jpg"			);
		Load( Combo,						"Combo.png"						);
		Load( RecordTable,					"RecordTable.png"				);
		Load( Pause,						"Pause.png"						);
		Load( SpaceBlack,					"SpaceBlack.jpg"				);
		Load( TeleportEff1,					"TeleportEffect1.png"			);
		Load( TeleportEff2,					"TeleportEffect2.png"			);
		Load( UFO,							"UFO.png"						);
		Load( Boss1,						"Boss1.png"						);
		Load( Turret,						"Turret.png"					);
		Load( Wheel,						"Wheel.png"						);
		Load( Shadow,						"Shadow.png"					);
		Load( Laser,						"Laser.png"						);
		Load( LaserEffect,					"LaserEffect.png"				);
		Load( EffectInBoss1,				"EffectInBoss1.png"				);
		Load( BangBoss,						"BangBoss.png"					);
		Load( Destroyer,					"Destroyer.png"					);
		Load( Spider,						"Spider.png"					);
		Load( Boss2,						"Boss2.png"						);
		Load( PirateStation,				"PirateStation.png"				);
		Load( Locust,						"Locust.png"					);
		Load( GopherQuad,					"GopherQuad.png"				);
		Load( CatchGopher,					"CatchGopher.png"				);
		Load( Meteor,						"Meteor.png"					);
		Load( Light,						"Light.png"						);
		Load( UFO2,							"UFO2.png"						);
		Load( Border,						"Border.png"					);
		Load( White,						"White.png"						);
		Load( Rainbow2,						"CreatorEffect.png"				);
		Load( SFML,							"SFML.png"						);
	}

	~Texture(void){}
};